services:
  - type: web
    name: rg-link-server
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3333
      - key: SENDGRID_API_KEY
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: SPREADSHEET_ID
        sync: false
    healthCheckPath: /
    numInstances: 1
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
